`default_nettype none

`define FRAME_MEMORY_START (16'h1000)
`define FRAME_MEMORY_END   (16'h2000)
`define DEFAULT_FRAME_ADDRESS (`FRAME_MEMORY_START)

`define SID1_START    (16'h0100)
`define SID1_END      (16'h0120)

`define FILTER_START (16'h0200)
`define FILTER_END   (16'h02FF)

`define MATRIX_START (16'h0400)
`define MATRIX_END   (16'h040F)

`define SID_OFFSET_VOICE1_FREQ_L  (6'h00)
`define SID_OFFSET_VOICE1_FREQ_H  (6'h01)
`define SID_OFFSET_VOICE1_PW_L    (6'h02)
`define SID_OFFSET_VOICE1_PW_H    (6'h03)
`define SID_OFFSET_VOICE1_CONTROL (6'h04)
`define SID_OFFSET_VOICE1_ATTDEC  (6'h05)
`define SID_OFFSET_VOICE1_SSTREL  (6'h06)

`define SID_OFFSET_VOICE2_FREQ_L  (6'h07)
`define SID_OFFSET_VOICE2_FREQ_H  (6'h08)
`define SID_OFFSET_VOICE2_PW_L    (6'h09)
`define SID_OFFSET_VOICE2_PW_H    (6'h0A)
`define SID_OFFSET_VOICE2_CONTROL (6'h0B)
`define SID_OFFSET_VOICE2_ATTDEC  (6'h0C)
`define SID_OFFSET_VOICE2_SSTREL  (6'h0D)

`define SID_OFFSET_VOICE3_FREQ_L  (6'h0E)
`define SID_OFFSET_VOICE3_FREQ_H  (6'h0F)
`define SID_OFFSET_VOICE3_PW_L    (6'h10)
`define SID_OFFSET_VOICE3_PW_H    (6'h11)
`define SID_OFFSET_VOICE3_CONTROL (6'h12)
`define SID_OFFSET_VOICE3_ATTDEC  (6'h13)
`define SID_OFFSET_VOICE3_SSTREL  (6'h14)

`define SID_OFFSET_FILT_L         (6'h15)
`define SID_OFFSET_FILT_H         (6'h16)
`define SID_OFFSET_RESFILT        (6'h17)
`define SID_OFFSET_MODEVOL        (6'h18)
`define SID_OFFSET_FILT_Q_L       (6'h19)
`define SID_OFFSET_FILT_Q_H       (6'h20)


`define FILTER_OFFSET_CONTROL     (8'h00)
`define FILTER_OFFSET_GAINS_START (8'h02)
`define FILTER_OFFSET_COEF_START  (8'h20)


`define MATRIX_CONTROL    (4'h0)
`define MATRIX_BRIGHTNESS (4'h1)
`define MATRIX_ADDR_L     (4'h2)
`define MATRIX_ADDR_H     (4'h3)


